name: currency_converter_services
description: Services for currency converter
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  currency_converter_models:
    path: ../models

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
