name: currency_converter_mobile
description: Currency converter in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  currency_converter_models:
    path: ../models
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  form_field_validator: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
