name: currency_converter_mobile
description: Currency converter in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  currency_converter_models:
    path: ../models
  currency_converter_bloc:
    path: ../bloc
  currency_converter_services:
    path: ../services
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  form_field_validator: ^1.0.1
  flutter_bloc: ^3.2.0
  localstorage: ^3.0.1+4

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
