name: currency_converter_bloc
description: Business logic for currency converter
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^3.0.0
  currency_converter_models:
    path: ../models
  currency_converter_services:
    path: ../services

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
